client/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, TextAreaField
from wtforms.validators import DataRequired, Email


class IncidentForm(FlaskForm):
    name = StringField("ФИО:", validators=[DataRequired('Поле не заполнено')])
    email = EmailField('Почта:', validators=[DataRequired(),
                                             Email(message='Введен некорректный email адрес')])

    subject = StringField('Тема', validators=[DataRequired()])
    description = TextAreaField('Описание', validators=[DataRequired()])
    submit = SubmitField("Отправить")

client/app/__init__.py
from flask import Flask


def create_app(config) -> Flask:
    """
    Creates app and register Blueprints

    :returns: app
    :rtype: Flask
    """
    app = Flask(__name__)
    app.config.from_object(config)

    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

client/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

client/app/main/routes.py
from flask import render_template, redirect, url_for

from . import main
from .forms import IncidentForm
from ...utils.data_loader import send_incident


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/incidents', methods=["POST", "GET"])
def incidents():
    form = IncidentForm()
    if form.validate_on_submit():
        send_incident(form.name.data,
                      form.email.data,
                      form.subject.data,
                      form.description.data)
        return redirect(url_for('main.incident_send_success'))

    return render_template('incidents.html', form=form)


@main.route('/incidents/success')
def incident_send_success():
    return render_template('incident_send_success.html')

client/app/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    <title>{% block title %}{% endblock %}</title>
    {% block script %}{% endblock %}
</head>
<body>
<header class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Header">
    <div class="container">
        <a href="{{ url_for('main.index') }}" class="navbar-brand">Фиксик - Клиент</a>
        <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#header" aria-controls="header">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end bg-dark cropped" data-bs-scroll="true" tabindex="-1" id="header" aria-labelledby="headerLable">
            <ul class="navbar-nav ms-sm-auto mb-2 mx-3 mx-sm-0 mb-sm-0">

                <li class="nav-item">
                    <a class="nav-link active text-decoration-none" href="{{ url_for('main.incidents') }}">Отправить заявку</a>
                </li>

            </ul>
        </div>
    </div>
</header>
<main id="content">{% block main %}{% endblock %}</main>
{% block tail_js %}{% endblock %}
{% block tail %}{% endblock %}
</body>
</html>

client/app/templates/incident_send_success.html
{% extends 'base.html' %}

{% block title %}
Заявка отправлена
{% endblock %}

{% block main %}
<div class="container">
    <h1>Ваша заявка успешно отправлена!</h1>
</div>

{% endblock %}

client/app/templates/incidents.html
{% extends 'base.html' %}

{% block title %}
Заявки
{% endblock %}

{% block main %}
<div class="form-signin text-center">
    <form method="post" class="form-contact">
        {{ form.hidden_tag() }}
        <h1 class="h3 mb-3 fw-normal">Для отправки заявки заполните форму:</h1>
        {% for cat, msg in get_flashed_messages(True) %}
            <div class="alert flash-{{cat}}">{{msg}}</div>
        {% endfor %}
        {% for field in form if field.name not in ['csrf_token', 'submit'] %}
            <div class="form-floating">
                {% if field.errors %}
                    {{ field(class="form-control") }}
                    <ul class="errors">
                        {% for error in field.errors %}
                            <li class="error">
                                <span class="err">
                                    {{ error }}
                                </span>
                            </li>
                        {% endfor %}
                    </ul>
                    {{ field.label(class="err", value=field.errors[0]) }}
                 {% else %}
                    {{ field(class="form-control") }}
                    {{ field.label() }}
                 {% endif %}
            </div>
        {% endfor %}

        <div>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</div>
    </form>
</div>

{% endblock %}

client/app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Добро пожаловать
{% endblock %}

{% block main %}
<div class="container">
    <h1>Веб сайт для клиентов компании «Ремонтный сервис компьютеров “Фиксик”»</h1>
</div>

{% endblock %}